### PR TITLE
Flkelly powershell greenfield

### PR DESCRIPTION
**Pull request by fskelly**
# Overview/Summary

PowerShell version of AVS Deployment
Json based for variables

Allows for full or staggered deployment

### Breaking Changes

1. *Replace me*
2. *Replace me*

## Testing Evidence

Tested with bugbash and improved with feedback from CSU

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale-for-AVS/pulls)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale-for-AVS/tree/main)
- [X] Performed testing and provided evidence.
- [X] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by prasad3017** [comment]
@khensler  Could you please review the PR and approve for PowerShell module?

**Comment by prasad3017** [comment]
@fskelly  Is this PR still needed as you are able to push the code?

**Comment by sblair01** [comment]
@fskelly @shaunjacob is this PR still applicable?

**Comment by vivalada** [comment]
@fskelly is this PR still applicable?

**Review by jchancellor-ms — APPROVED** [review]
Reviewed these changes and resolved the lone merge conflict.  Will need to add an item to re-run testing on these changes to ensure that there aren't api or cli changes that may impact functionality since this was tested some time ago.

**Pull request merged**
