### PR TITLE
Added setStoragePolicy.ps1

### PR DESCRIPTION
**Pull request by fguerri**
# Overview/Summary

This PR adds the Automation script "setStoragePolicy.ps1". The script invokes the AVS command "Set-VMStoragePolicy" on a set of AVS VMs. The names of the VMs are provided in an array input parameter. 

## This PR fixes/adds/changes/removes

Adds BrownField/Addons/AUTOMATION/setStoragePolicy.ps1

### Breaking Changes

None

## Testing Evidence

The following test has been successfully executed on an AVS Private Cloud.
1) Test VMs vm1 and vm2 have been created with storage policy = "vSAN Default Storage Policy"
2) The script has been executed as follows: "setStoragePolicy.ps1 -PrivateCloudName TESTPRIVATECLOUDNAME -PrivateCloudResourceGroup TESTRG-PrivateCloud -StoragePolicyName "Thin Provision" -VmNames 'vm1','vm2'
3) The storage policy for test VMs has been confirmed to be "Thin Provision" after the command executions terminate on the AVS Private Cloud
4) The command executions have been confirmed to terminate successfully without errors in the Azure portal.

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale-for-AVS/pulls)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale-for-AVS/tree/main)
- [x] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.

### CODE REVIEW

**Review by ScottHolden — CHANGES_REQUESTED** [review]
Hey, looks great! Can we add:

- [x] Move this from the 'Addons' folder to a 'RunCommands' folder with a 'StoragePolicy/PowerShell' folder
- [x] Add readme.md to the RunCommands & 'StoragePolicy' folders
- [x] Add a link to the 'StoragePolicy' folder from the 'Brownfield' readme.md

**Comment by prasad3017** [comment]
@fguerri  Kindly look at Scott comments

**Comment by fguerri** [comment]
hi @ScottHolden thank you for your comments. The changes you requested have been pushed.
cc @prasad3017

**Review by ScottHolden — APPROVED** [review]
Looks fantastic! Happy for you to merge 🙂

**Comment by fguerri** [comment]
Thank you @ScottHolden for your help and guidance!!

**Comment by joesarabia** [comment]
My opinion on this one is that we should not direct this operation through az cli, but instead go use PowerCLI to vCenter as cloudadmin has the privileges to run Set-VM -StoragePolicy directly (however just not through vSphere Client).

**Comment by fguerri** [comment]
> My opinion on this one is that we should not direct this operation through az cli, but instead go use PowerCLI to vCenter as cloudadmin has the privileges to run Set-VM -StoragePolicy directly (however just not through vSphere Client).

Hello @joesarabia I see your point and do not disagree. I was not the one who collected the customer ask that led to this development (maybe the customer wanted to use the AVS API instead of PowerCLI so that network access to the vCenter Server is not needed?) @prasad3017 might have more details.

**Pull request merged**
