### PR TITLE
Terraforming brownfield/monitoring

### PR DESCRIPTION
**Pull request by lrivallain**
# Overview/Summary

Hi, here are a set of terraform configurations to setup monitoring-related components on AVS.

I tried to align with most of the content of the existing (arm & bicep) methods.

## This PR fixes/adds/changes/removes

1. Add *AVS-Dashboard* terraform-ed component
2. Add *AVS-Service-Health* terraform-ed component
3. Add *AVS-Utilization-Alerts* terraform-ed component
4. Updated Readme files for the 3 above items.

I also updated the `.gitignore` file to facilitate development.

### Breaking Changes

n/a

## Testing Evidence

- Tested on demo AVS deployment and deployed the following items:
image

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale-for-AVS/pulls)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale-for-AVS/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by ScottHolden** [comment]
Looks great to me! Pinging @shaunjacob to check it looks good and then it can be merged :)

**Comment by lrivallain** [comment]
Hi all. Any chance this can be merge ?

**Comment by prasad3017** [comment]
Checking on this

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lrivallain** [comment]
Hi @prasad3017 
Any update on review this ?
Kind regards

**Comment by prasad3017** [comment]
@jchancellor-ms  could you please review this PR?

**Comment by prasad3017** [comment]
@jchancellor-ms Can we merge this PR?

**Review by sblair01 — APPROVED** [review]

**Comment by sblair01** [comment]
@lrivallain apologies for the delay

**Pull request merged**
