### PR TITLE
fixed the location parameter

### PR DESCRIPTION
**Pull request by Mahesh-MSFT**
fixed the location parameter

### CODE REVIEW

**Comment by prasad3017** [comment]
@ScottHolden  To review this change

**Comment by sonmitt** [comment]
@Mahesh-MSFT - This branch has conflicting files which needs to be resolved before merging.
@prasad3017 -  We have recently received a new issue for the same concern (Remove Location parameter from the template). This PR needs a review.

**Comment by Mahesh-MSFT** [comment]
thanks @sonmitt . this pr developed merge conflict because it was not picked up early. we need to come up with a better plan how we handle old prs. inevitably, they will develop merge conflicts otherwise. i am working on this. thanks!

**Comment by ScottHolden** [comment]
Closing, duplicate of #99

**Pull request closed without merging**
