### PR TITLE
Adding TF code to create VM on AVS

### PR DESCRIPTION
**Pull request by khushal08**
# Terraform code to create the following resources within the AVS private cloud
1. DHCP profile
2. T1 Gateway
3. Workload Segment
4. Linux VM

## As part of this Pull Request I have

- [X ] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale-for-AVS/pulls)
- [ X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale-for-AVS/tree/main)
- [X ] Performed testing and provided evidence.
- [ X] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by khushal08** [comment]
@prasad3017 Can you please help review?

**Comment by prasad3017** [comment]
@jchancellor-ms could you please help to review?

@rvandenbedem  Looking for your feedback and sign off

**Comment by prasad3017** [comment]
@jchancellor-ms  could you please review?

**Review by jchancellor-ms — COMMENTED** [review]
Code looks good.  I would like to suggest that in the next release we move the network and vm  modules into the modules directory and either add the root module there also or move the root module into the scenarios directory.  I'm working on a module that will deploy a linux server into a hub and then run terraform to deploy these vmware modules automatically as part of a scenario or lab buildout.  

@rvandenbedem - I'll leave final approval to you.

**Review by rvandenbedem — APPROVED** [review]

**Pull request merged**
