### PR TITLE
Flkelly powershell greenfield

### PR DESCRIPTION
**Pull request by fskelly**
# Overview/Summary

This PR add PowerShell functionality to the greenfield deployment option.

## This PR fixes/adds/changes/removes

1. *Adds PowerShell functionality to the greenfield deployment*
2. *Breaks down greenfield into smaller pieces of code similar to "modules"*

### Breaking Changes

1. *None*

## Testing Evidence

- Run in FastTrack for Azure environments multiple times and is now the default tool for creating an SDDC in EMEA

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale-for-AVS/pulls)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale-for-AVS/tree/main)
- [X] Performed testing and provided evidence.
- [X] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by fskelly** [comment]
@prasad3017 - could you review when you get a chance?

**Review by prasad3017 — DISMISSED** [review]

**Comment by prasad3017** [comment]
@fskelly  kindly let us know @aarhoden-msft @fguerri  are able to test the code so that I can request Rene to review the code.

**Comment by fskelly** [comment]
still awaiting feedback from @aarhoden-msft  @fguerri , will let everyone know once i have received this.

**Review by sblair01 — APPROVED** [review]
Mostly cosmetic changes. LGTM!

**Comment by prasad3017** [comment]
@sblair01 this is still going through testing. It looks like merged but will let @fskelly  confirm if we need to have a PR with the testing feedback

**Pull request merged**
