### PR TITLE
Update of spellcheck GitHub Action to version 0.29.0

### PR DESCRIPTION
**Pull request by jonasbn**
Hello 

As the maintainer of the [spellcheck GitHub action](https://github.com/marketplace/actions/github-spellcheck-action) I am _sunsetting_ version 0.16.0 as by the proposed [sunset policy](https://github.com/rojopolis/spellcheck-github-actions/wiki#sunset-policy)

I just updated the action to version 0.26.0, so this PR offers an update to the latest version.

Let me know if you have any issues with the proposed PR and I will try to accommodate.

I can recommend [Dependabot](https://github.com/dependabot) for keeping your GitHub actions up to date, alternatively there are [Renovate](https://github.com/marketplace/renovate), if you want a PR proposing a basic configuration for Dependabot, please let me know.

Happy new year

jonasbn

### CODE REVIEW

**Comment by prasad3017** [comment]
@shaunjacob @jchancellor-ms  could you please check this PR and approve?

**Comment by jonasbn** [comment]
Any updates on this?

**Review by sblair01 — APPROVED** [review]
Approved!

**Comment by sblair01** [comment]
@jonasbn the spellcheck is very strict. There are some legitimate spelling errors, but they are hard to see. The spellcheck is complaining about every code variable name and "Expressroute" which is the standard way we spell that in Azure amongst other things. Please see this PR for an example: https://github.com/Azure/Enterprise-Scale-for-AVS/actions/runs/4243586884/jobs/7376529387

**Comment by jonasbn** [comment]
Hi @sblair01 

I will have a look and get back to you

**Comment by jonasbn** [comment]
Hi @sblair01 

Okay I can see there are quite a few things to work on.

First I have a suggestion for a configuration improvement.

1. Add the `pymdownx.superfences` so that fenced coding structures are handled properly.

This was added to [the documentation](https://github.com/rojopolis/spellcheck-github-actions#specify-code-not-to-have-spelling-checked) fairly recently, so I understand if you have missed it.

`.github/config/spellcheck.yml`

```yaml
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
  - pyspelling.filters.html:
```

Let me know if you want this as a PR instead of a comment.

2. ignore casing, the example you provide with "Expressroute" is interesting since it is in your local dictionary as "ExpressRoute", but since the default is case sensitive the does not excempt: "Expressroute"

I would recommend that you correct it in all the places, but [ignoring case](https://github.com/rojopolis/spellcheck-github-actions#slimming-your-wordlist-by-ignoring-case) could be a start to get the situation under control.

`.github/config/spellcheck.yml`

```yaml
  aspell:
    lang: en
    ignore-case: true
```

Let me know if you want this as a PR instead of a comment.

3. If you want me to help you to get the action to pass with all corrections made and the local dictionary expanded with what is handled please let me know and I will create a PR, it will become somewhat large, but it will only affect Markdown files, so a review should be strait forward, but time consuming.

**Comment by jonasbn** [comment]
Hi @sblair01 

Please see PR #227 with my proposal.

**Pull request merged**
