### PR TITLE
Updated Jumpbox file case to match

### LINKED ISSUE #79: Capitalization on Jumpbox directory
the bicep template references JumpBox while the directory in the repo is Jumpbox.  This causes an issue w/ capitalization aware filesystems:

/avs-template.bicep(97,16) : Error BCP104: The referenced module has errors.
/Modules/JumpBox.bicep(16,15) : Error BCP091: An error occurred reading file. Could not find a part of the path /Modules/JumpBox/JumpBoxSubnet.bicep'.
/Modules/JumpBox.bicep(31,16) : Error BCP091: An error occurred reading file. Could not find a part of the path /Modules/JumpBox/Bastion.bicep'.
/Modules/JumpBox.bicep(41,11) : Error BCP091: An error occurred reading file. Could not find a part of the path /Modules/JumpBox/JumpBoxVM.bicep'.
/Modules/JumpBox.bicep(54,35) : Error BCP062: The referenced declaration with name "VM" is not valid.

### PR DESCRIPTION
**Pull request by ScottHolden**
# Overview/Summary

This resolves #79 by fixing the file names and references to match the expected casing. ARM template has been rebuilt to validate changes.

Validated on Windows & Linux.

This will need to be validated on MacOS as well.

### CODE REVIEW

**Review by prasad3017 — APPROVED** [review]
Thanks Scott

**Comment by sblair01** [comment]
@ScottHolden - this has been open for sometime. Is it still pending or can we close?

**Review by sblair01 — APPROVED** [review]

**Comment by sblair01** [comment]
Reached out to @ScottHolden and cc'd @shaunjacob offline to resolve the merge conflicts

**Comment by prasad3017** [comment]
@ScottHolden  Is this still required PR?

**Pull request closed without merging**
