### PR TITLE
added pid

### PR DESCRIPTION
**Pull request by Mahesh-MSFT**
added pid

### CODE REVIEW

**Comment by ScottHolden** [comment]
Looks good to me!

**Comment by ScottHolden** [comment]
Looks good to me!

**Review by khensler — APPROVED** [review]
looks good to me

**Comment by Mahesh-MSFT** [comment]
adding @jchancellor-ms. he has some comments on usage of `SmartConnectNoSSL` from security perspective. @khensler - are there any security risks associated with `SmartConnectNoSSL`?

**Comment by khensler** [comment]
i used smartconnectnossl to bypass ssl certificate verification since AVS uses self signed certs.

**Comment by jchancellor-ms** [comment]
Got it.  I misread that as we were connecting without ssl.  Thanks for the clarification.

**Pull request merged**
